### ISSUE TITLE
No public constructor is available for type OpenQA.Selenium.IWebDriver exception

### ISSUE THREAD

**Issue by 48x16** [AutomateThePlanet/BELLATRIX#12] opened 2022-03-22 11:32 UTC
Hi,

Currently using the latest codebase on Windows.
Running any Bellatrix.Web.Tests (BasicTable_Has_Header for example) triggers the following exception.

I traced the code through and it appears the following line within the TestsIniatilze.cs class:

![BellatrixPossibleBug1code](https://user-images.githubusercontent.com/37348105/159471468-2f673c86-a967-41f0-81e1-26929490bd04.png)

Raises the following exception:

![BellatrixPossibleBug1](https://user-images.githubusercontent.com/37348105/159471560-b78a5dde-6356-44a2-947c-969d6554e782.png)

My assumption is that it cannot resolve something that doesn't exist, but I don't know the fix to apply to help you.

I have been using the edge browser, and the chrome browser. If I could have some more information around the issue, and any workaround please? It doesn't affect the test execution so not a critical issue.

Many thanks for your efforts, it's an excellent framework.

**Comment by angelovstanton** [comment] 2022-03-22 12:07
Thank you for reporting! I have just debugged it but I couldn't figure out quickly what is the problem. Probably it is a regression bug from the last release because there we included some enhancements for these components. I contacted the developer who worked on it and we will see what we can do about it.

**Comment by angelovstanton** [comment] 2022-03-28 14:19
the bug should be fixed, I have just submitted the code

**Closed by angelovstanton** 2022-03-28 14:19 UTC
